# -*- coding: utf-8 -*-
"""AI FIRSTLAB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkLFd1b8EohDtZCNS1LmktwyNGavBWK2

# ADDITION
"""

a = 6
b = 4
c = (a+b)
print (c)

"""# SUBTRACTION"""

a = 5
b = 3
c = 2
d = (a-b-c)
print(d)

"""# MULTIPLICATION

"""

a = 5
b = 3
c = 2
d = (a*b*c)
print(d)

"""# DIVISION"""

a = 50
b = 5
c = (a/b)
print(c)